---
# tasks file for install_apache_role
#
- name: Installing Apache
  yum:
    name: "{{  apache_name  }}"
    state: latest

- name: Filling template and sending it to remote host
  template:
    src: index.j2
    dest: "{{  dest_folder  }}/index.html"
  notify: Restart Apache  

- name: Turning Apache on
  service: 
    name:  "{{  apache_name  }}"
    state: started
    enabled: yes

- name: Checking Apache status
  shell: "systemctl is-active {{  apache_name  }}"
  register: result
  failed_when: result.stdout != "active"

