---
- name: Install Apache
  hosts: centos
  become: true
  
 
  tasks:
    - name: Install Apache
      yum: name=httpd state=installed
    
    - name: Create index file
      copy: dest=/var/www/html/index.html content="Welcome to my web server"
      notify: Restart Apache

    - name: Install firewalld
      yum: name=firewalld state=installed

    - name: Start firewalld
      service: name=firewalld state=started enabled=yes

    - name: Open FW
      firewalld: port=80/tcp permanent=true state=enabled immediate=yes

    - name: Start Apache and enable on boot
      service: name=httpd state=started enabled=yes

  handlers:
    - name: Restart Apache
      service: name=httpd state=restarted    
